# fly.toml app configuration file generated for debating-live on 2023-08-10T11:10:20-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "debating-live"
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
